version: "3"
services:
  node:
    build: .
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
    ports:
      - "8001:80"
    volumes:
      - .:/home/node/app
      - ./dist:/usr/local/apache2/htdocs/
    networks:
      - default

networks:
  default:
    driver: bridge
    name: my-network
